{{ if .Values.rbac.install }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-role
rules:
- apiGroups:
  - example.com
  resources:
  - qiniunginxs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - apps
  - extensions
  resources:
  - statefulsets
  - deployments
  - daemonsets
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-bind
subjects:
- kind: ServiceAccount
  name: operator-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: operator-role
{{ end }}
