kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-bind
subjects:
- kind: ServiceAccount
  name: operator-sa
  namespace: opdemo
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: operator-role