kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: demo2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: liqingsanjin/jingx:v1.0.41
